apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::277707111654:role/CodeBuildEKSRole
      username: build-role
      groups:
        - system:masters
